# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/boula/source/repos/openauto

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/boula/source/repos/openauto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/boula/source/repos/openauto/CMakeFiles /mnt/c/Users/boula/source/repos/openauto//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/boula/source/repos/openauto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named autoapp

# Build rule for target.
autoapp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 autoapp
.PHONY : autoapp

# fast build rule for target.
autoapp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/build
.PHONY : autoapp/fast

#=============================================================================
# Target rules for targets named btservice

# Build rule for target.
btservice: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 btservice
.PHONY : btservice

# fast build rule for target.
btservice/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/build
.PHONY : btservice/fast

#=============================================================================
# Target rules for targets named autoapp_autogen_timestamp_deps

# Build rule for target.
autoapp_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 autoapp_autogen_timestamp_deps
.PHONY : autoapp_autogen_timestamp_deps

# fast build rule for target.
autoapp_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp_autogen_timestamp_deps.dir/build.make CMakeFiles/autoapp_autogen_timestamp_deps.dir/build
.PHONY : autoapp_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named autoapp_autogen

# Build rule for target.
autoapp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 autoapp_autogen
.PHONY : autoapp_autogen

# fast build rule for target.
autoapp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp_autogen.dir/build.make CMakeFiles/autoapp_autogen.dir/build
.PHONY : autoapp_autogen/fast

#=============================================================================
# Target rules for targets named btservice_autogen_timestamp_deps

# Build rule for target.
btservice_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 btservice_autogen_timestamp_deps
.PHONY : btservice_autogen_timestamp_deps

# fast build rule for target.
btservice_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice_autogen_timestamp_deps.dir/build.make CMakeFiles/btservice_autogen_timestamp_deps.dir/build
.PHONY : btservice_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named btservice_autogen

# Build rule for target.
btservice_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 btservice_autogen
.PHONY : btservice_autogen

# fast build rule for target.
btservice_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice_autogen.dir/build.make CMakeFiles/btservice_autogen.dir/build
.PHONY : btservice_autogen/fast

autoapp_autogen/GBFAFXFCVO/qrc_resources.o: autoapp_autogen/GBFAFXFCVO/qrc_resources.cpp.o
.PHONY : autoapp_autogen/GBFAFXFCVO/qrc_resources.o

# target to build an object file
autoapp_autogen/GBFAFXFCVO/qrc_resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/autoapp_autogen/GBFAFXFCVO/qrc_resources.cpp.o
.PHONY : autoapp_autogen/GBFAFXFCVO/qrc_resources.cpp.o

autoapp_autogen/GBFAFXFCVO/qrc_resources.i: autoapp_autogen/GBFAFXFCVO/qrc_resources.cpp.i
.PHONY : autoapp_autogen/GBFAFXFCVO/qrc_resources.i

# target to preprocess a source file
autoapp_autogen/GBFAFXFCVO/qrc_resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/autoapp_autogen/GBFAFXFCVO/qrc_resources.cpp.i
.PHONY : autoapp_autogen/GBFAFXFCVO/qrc_resources.cpp.i

autoapp_autogen/GBFAFXFCVO/qrc_resources.s: autoapp_autogen/GBFAFXFCVO/qrc_resources.cpp.s
.PHONY : autoapp_autogen/GBFAFXFCVO/qrc_resources.s

# target to generate assembly for a file
autoapp_autogen/GBFAFXFCVO/qrc_resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/autoapp_autogen/GBFAFXFCVO/qrc_resources.cpp.s
.PHONY : autoapp_autogen/GBFAFXFCVO/qrc_resources.cpp.s

autoapp_autogen/mocs_compilation.o: autoapp_autogen/mocs_compilation.cpp.o
.PHONY : autoapp_autogen/mocs_compilation.o

# target to build an object file
autoapp_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/autoapp_autogen/mocs_compilation.cpp.o
.PHONY : autoapp_autogen/mocs_compilation.cpp.o

autoapp_autogen/mocs_compilation.i: autoapp_autogen/mocs_compilation.cpp.i
.PHONY : autoapp_autogen/mocs_compilation.i

# target to preprocess a source file
autoapp_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/autoapp_autogen/mocs_compilation.cpp.i
.PHONY : autoapp_autogen/mocs_compilation.cpp.i

autoapp_autogen/mocs_compilation.s: autoapp_autogen/mocs_compilation.cpp.s
.PHONY : autoapp_autogen/mocs_compilation.s

# target to generate assembly for a file
autoapp_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/autoapp_autogen/mocs_compilation.cpp.s
.PHONY : autoapp_autogen/mocs_compilation.cpp.s

btservice_autogen/mocs_compilation.o: btservice_autogen/mocs_compilation.cpp.o
.PHONY : btservice_autogen/mocs_compilation.o

# target to build an object file
btservice_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/btservice_autogen/mocs_compilation.cpp.o
.PHONY : btservice_autogen/mocs_compilation.cpp.o

btservice_autogen/mocs_compilation.i: btservice_autogen/mocs_compilation.cpp.i
.PHONY : btservice_autogen/mocs_compilation.i

# target to preprocess a source file
btservice_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/btservice_autogen/mocs_compilation.cpp.i
.PHONY : btservice_autogen/mocs_compilation.cpp.i

btservice_autogen/mocs_compilation.s: btservice_autogen/mocs_compilation.cpp.s
.PHONY : btservice_autogen/mocs_compilation.s

# target to generate assembly for a file
btservice_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/btservice_autogen/mocs_compilation.cpp.s
.PHONY : btservice_autogen/mocs_compilation.cpp.s

src/autoapp/App.o: src/autoapp/App.cpp.o
.PHONY : src/autoapp/App.o

# target to build an object file
src/autoapp/App.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/App.cpp.o
.PHONY : src/autoapp/App.cpp.o

src/autoapp/App.i: src/autoapp/App.cpp.i
.PHONY : src/autoapp/App.i

# target to preprocess a source file
src/autoapp/App.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/App.cpp.i
.PHONY : src/autoapp/App.cpp.i

src/autoapp/App.s: src/autoapp/App.cpp.s
.PHONY : src/autoapp/App.s

# target to generate assembly for a file
src/autoapp/App.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/App.cpp.s
.PHONY : src/autoapp/App.cpp.s

src/autoapp/Configuration/Configuration.o: src/autoapp/Configuration/Configuration.cpp.o
.PHONY : src/autoapp/Configuration/Configuration.o

# target to build an object file
src/autoapp/Configuration/Configuration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Configuration/Configuration.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/autoapp/Configuration/Configuration.cpp.o
.PHONY : src/autoapp/Configuration/Configuration.cpp.o

src/autoapp/Configuration/Configuration.i: src/autoapp/Configuration/Configuration.cpp.i
.PHONY : src/autoapp/Configuration/Configuration.i

# target to preprocess a source file
src/autoapp/Configuration/Configuration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Configuration/Configuration.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/autoapp/Configuration/Configuration.cpp.i
.PHONY : src/autoapp/Configuration/Configuration.cpp.i

src/autoapp/Configuration/Configuration.s: src/autoapp/Configuration/Configuration.cpp.s
.PHONY : src/autoapp/Configuration/Configuration.s

# target to generate assembly for a file
src/autoapp/Configuration/Configuration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Configuration/Configuration.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/autoapp/Configuration/Configuration.cpp.s
.PHONY : src/autoapp/Configuration/Configuration.cpp.s

src/autoapp/Configuration/RecentAddressesList.o: src/autoapp/Configuration/RecentAddressesList.cpp.o
.PHONY : src/autoapp/Configuration/RecentAddressesList.o

# target to build an object file
src/autoapp/Configuration/RecentAddressesList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Configuration/RecentAddressesList.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/autoapp/Configuration/RecentAddressesList.cpp.o
.PHONY : src/autoapp/Configuration/RecentAddressesList.cpp.o

src/autoapp/Configuration/RecentAddressesList.i: src/autoapp/Configuration/RecentAddressesList.cpp.i
.PHONY : src/autoapp/Configuration/RecentAddressesList.i

# target to preprocess a source file
src/autoapp/Configuration/RecentAddressesList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Configuration/RecentAddressesList.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/autoapp/Configuration/RecentAddressesList.cpp.i
.PHONY : src/autoapp/Configuration/RecentAddressesList.cpp.i

src/autoapp/Configuration/RecentAddressesList.s: src/autoapp/Configuration/RecentAddressesList.cpp.s
.PHONY : src/autoapp/Configuration/RecentAddressesList.s

# target to generate assembly for a file
src/autoapp/Configuration/RecentAddressesList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Configuration/RecentAddressesList.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/autoapp/Configuration/RecentAddressesList.cpp.s
.PHONY : src/autoapp/Configuration/RecentAddressesList.cpp.s

src/autoapp/Projection/DummyBluetoothDevice.o: src/autoapp/Projection/DummyBluetoothDevice.cpp.o
.PHONY : src/autoapp/Projection/DummyBluetoothDevice.o

# target to build an object file
src/autoapp/Projection/DummyBluetoothDevice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/DummyBluetoothDevice.cpp.o
.PHONY : src/autoapp/Projection/DummyBluetoothDevice.cpp.o

src/autoapp/Projection/DummyBluetoothDevice.i: src/autoapp/Projection/DummyBluetoothDevice.cpp.i
.PHONY : src/autoapp/Projection/DummyBluetoothDevice.i

# target to preprocess a source file
src/autoapp/Projection/DummyBluetoothDevice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/DummyBluetoothDevice.cpp.i
.PHONY : src/autoapp/Projection/DummyBluetoothDevice.cpp.i

src/autoapp/Projection/DummyBluetoothDevice.s: src/autoapp/Projection/DummyBluetoothDevice.cpp.s
.PHONY : src/autoapp/Projection/DummyBluetoothDevice.s

# target to generate assembly for a file
src/autoapp/Projection/DummyBluetoothDevice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/DummyBluetoothDevice.cpp.s
.PHONY : src/autoapp/Projection/DummyBluetoothDevice.cpp.s

src/autoapp/Projection/InputDevice.o: src/autoapp/Projection/InputDevice.cpp.o
.PHONY : src/autoapp/Projection/InputDevice.o

# target to build an object file
src/autoapp/Projection/InputDevice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/InputDevice.cpp.o
.PHONY : src/autoapp/Projection/InputDevice.cpp.o

src/autoapp/Projection/InputDevice.i: src/autoapp/Projection/InputDevice.cpp.i
.PHONY : src/autoapp/Projection/InputDevice.i

# target to preprocess a source file
src/autoapp/Projection/InputDevice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/InputDevice.cpp.i
.PHONY : src/autoapp/Projection/InputDevice.cpp.i

src/autoapp/Projection/InputDevice.s: src/autoapp/Projection/InputDevice.cpp.s
.PHONY : src/autoapp/Projection/InputDevice.s

# target to generate assembly for a file
src/autoapp/Projection/InputDevice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/InputDevice.cpp.s
.PHONY : src/autoapp/Projection/InputDevice.cpp.s

src/autoapp/Projection/LocalBluetoothDevice.o: src/autoapp/Projection/LocalBluetoothDevice.cpp.o
.PHONY : src/autoapp/Projection/LocalBluetoothDevice.o

# target to build an object file
src/autoapp/Projection/LocalBluetoothDevice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/LocalBluetoothDevice.cpp.o
.PHONY : src/autoapp/Projection/LocalBluetoothDevice.cpp.o

src/autoapp/Projection/LocalBluetoothDevice.i: src/autoapp/Projection/LocalBluetoothDevice.cpp.i
.PHONY : src/autoapp/Projection/LocalBluetoothDevice.i

# target to preprocess a source file
src/autoapp/Projection/LocalBluetoothDevice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/LocalBluetoothDevice.cpp.i
.PHONY : src/autoapp/Projection/LocalBluetoothDevice.cpp.i

src/autoapp/Projection/LocalBluetoothDevice.s: src/autoapp/Projection/LocalBluetoothDevice.cpp.s
.PHONY : src/autoapp/Projection/LocalBluetoothDevice.s

# target to generate assembly for a file
src/autoapp/Projection/LocalBluetoothDevice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/LocalBluetoothDevice.cpp.s
.PHONY : src/autoapp/Projection/LocalBluetoothDevice.cpp.s

src/autoapp/Projection/OMXVideoOutput.o: src/autoapp/Projection/OMXVideoOutput.cpp.o
.PHONY : src/autoapp/Projection/OMXVideoOutput.o

# target to build an object file
src/autoapp/Projection/OMXVideoOutput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/OMXVideoOutput.cpp.o
.PHONY : src/autoapp/Projection/OMXVideoOutput.cpp.o

src/autoapp/Projection/OMXVideoOutput.i: src/autoapp/Projection/OMXVideoOutput.cpp.i
.PHONY : src/autoapp/Projection/OMXVideoOutput.i

# target to preprocess a source file
src/autoapp/Projection/OMXVideoOutput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/OMXVideoOutput.cpp.i
.PHONY : src/autoapp/Projection/OMXVideoOutput.cpp.i

src/autoapp/Projection/OMXVideoOutput.s: src/autoapp/Projection/OMXVideoOutput.cpp.s
.PHONY : src/autoapp/Projection/OMXVideoOutput.s

# target to generate assembly for a file
src/autoapp/Projection/OMXVideoOutput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/OMXVideoOutput.cpp.s
.PHONY : src/autoapp/Projection/OMXVideoOutput.cpp.s

src/autoapp/Projection/QtAudioInput.o: src/autoapp/Projection/QtAudioInput.cpp.o
.PHONY : src/autoapp/Projection/QtAudioInput.o

# target to build an object file
src/autoapp/Projection/QtAudioInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/QtAudioInput.cpp.o
.PHONY : src/autoapp/Projection/QtAudioInput.cpp.o

src/autoapp/Projection/QtAudioInput.i: src/autoapp/Projection/QtAudioInput.cpp.i
.PHONY : src/autoapp/Projection/QtAudioInput.i

# target to preprocess a source file
src/autoapp/Projection/QtAudioInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/QtAudioInput.cpp.i
.PHONY : src/autoapp/Projection/QtAudioInput.cpp.i

src/autoapp/Projection/QtAudioInput.s: src/autoapp/Projection/QtAudioInput.cpp.s
.PHONY : src/autoapp/Projection/QtAudioInput.s

# target to generate assembly for a file
src/autoapp/Projection/QtAudioInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/QtAudioInput.cpp.s
.PHONY : src/autoapp/Projection/QtAudioInput.cpp.s

src/autoapp/Projection/QtAudioOutput.o: src/autoapp/Projection/QtAudioOutput.cpp.o
.PHONY : src/autoapp/Projection/QtAudioOutput.o

# target to build an object file
src/autoapp/Projection/QtAudioOutput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/QtAudioOutput.cpp.o
.PHONY : src/autoapp/Projection/QtAudioOutput.cpp.o

src/autoapp/Projection/QtAudioOutput.i: src/autoapp/Projection/QtAudioOutput.cpp.i
.PHONY : src/autoapp/Projection/QtAudioOutput.i

# target to preprocess a source file
src/autoapp/Projection/QtAudioOutput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/QtAudioOutput.cpp.i
.PHONY : src/autoapp/Projection/QtAudioOutput.cpp.i

src/autoapp/Projection/QtAudioOutput.s: src/autoapp/Projection/QtAudioOutput.cpp.s
.PHONY : src/autoapp/Projection/QtAudioOutput.s

# target to generate assembly for a file
src/autoapp/Projection/QtAudioOutput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/QtAudioOutput.cpp.s
.PHONY : src/autoapp/Projection/QtAudioOutput.cpp.s

src/autoapp/Projection/QtVideoOutput.o: src/autoapp/Projection/QtVideoOutput.cpp.o
.PHONY : src/autoapp/Projection/QtVideoOutput.o

# target to build an object file
src/autoapp/Projection/QtVideoOutput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/QtVideoOutput.cpp.o
.PHONY : src/autoapp/Projection/QtVideoOutput.cpp.o

src/autoapp/Projection/QtVideoOutput.i: src/autoapp/Projection/QtVideoOutput.cpp.i
.PHONY : src/autoapp/Projection/QtVideoOutput.i

# target to preprocess a source file
src/autoapp/Projection/QtVideoOutput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/QtVideoOutput.cpp.i
.PHONY : src/autoapp/Projection/QtVideoOutput.cpp.i

src/autoapp/Projection/QtVideoOutput.s: src/autoapp/Projection/QtVideoOutput.cpp.s
.PHONY : src/autoapp/Projection/QtVideoOutput.s

# target to generate assembly for a file
src/autoapp/Projection/QtVideoOutput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/QtVideoOutput.cpp.s
.PHONY : src/autoapp/Projection/QtVideoOutput.cpp.s

src/autoapp/Projection/RtAudioOutput.o: src/autoapp/Projection/RtAudioOutput.cpp.o
.PHONY : src/autoapp/Projection/RtAudioOutput.o

# target to build an object file
src/autoapp/Projection/RtAudioOutput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/RtAudioOutput.cpp.o
.PHONY : src/autoapp/Projection/RtAudioOutput.cpp.o

src/autoapp/Projection/RtAudioOutput.i: src/autoapp/Projection/RtAudioOutput.cpp.i
.PHONY : src/autoapp/Projection/RtAudioOutput.i

# target to preprocess a source file
src/autoapp/Projection/RtAudioOutput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/RtAudioOutput.cpp.i
.PHONY : src/autoapp/Projection/RtAudioOutput.cpp.i

src/autoapp/Projection/RtAudioOutput.s: src/autoapp/Projection/RtAudioOutput.cpp.s
.PHONY : src/autoapp/Projection/RtAudioOutput.s

# target to generate assembly for a file
src/autoapp/Projection/RtAudioOutput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/RtAudioOutput.cpp.s
.PHONY : src/autoapp/Projection/RtAudioOutput.cpp.s

src/autoapp/Projection/SequentialBuffer.o: src/autoapp/Projection/SequentialBuffer.cpp.o
.PHONY : src/autoapp/Projection/SequentialBuffer.o

# target to build an object file
src/autoapp/Projection/SequentialBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/SequentialBuffer.cpp.o
.PHONY : src/autoapp/Projection/SequentialBuffer.cpp.o

src/autoapp/Projection/SequentialBuffer.i: src/autoapp/Projection/SequentialBuffer.cpp.i
.PHONY : src/autoapp/Projection/SequentialBuffer.i

# target to preprocess a source file
src/autoapp/Projection/SequentialBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/SequentialBuffer.cpp.i
.PHONY : src/autoapp/Projection/SequentialBuffer.cpp.i

src/autoapp/Projection/SequentialBuffer.s: src/autoapp/Projection/SequentialBuffer.cpp.s
.PHONY : src/autoapp/Projection/SequentialBuffer.s

# target to generate assembly for a file
src/autoapp/Projection/SequentialBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/SequentialBuffer.cpp.s
.PHONY : src/autoapp/Projection/SequentialBuffer.cpp.s

src/autoapp/Projection/VideoOutput.o: src/autoapp/Projection/VideoOutput.cpp.o
.PHONY : src/autoapp/Projection/VideoOutput.o

# target to build an object file
src/autoapp/Projection/VideoOutput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/VideoOutput.cpp.o
.PHONY : src/autoapp/Projection/VideoOutput.cpp.o

src/autoapp/Projection/VideoOutput.i: src/autoapp/Projection/VideoOutput.cpp.i
.PHONY : src/autoapp/Projection/VideoOutput.i

# target to preprocess a source file
src/autoapp/Projection/VideoOutput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/VideoOutput.cpp.i
.PHONY : src/autoapp/Projection/VideoOutput.cpp.i

src/autoapp/Projection/VideoOutput.s: src/autoapp/Projection/VideoOutput.cpp.s
.PHONY : src/autoapp/Projection/VideoOutput.s

# target to generate assembly for a file
src/autoapp/Projection/VideoOutput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Projection/VideoOutput.cpp.s
.PHONY : src/autoapp/Projection/VideoOutput.cpp.s

src/autoapp/Service/AndroidAutoEntity.o: src/autoapp/Service/AndroidAutoEntity.cpp.o
.PHONY : src/autoapp/Service/AndroidAutoEntity.o

# target to build an object file
src/autoapp/Service/AndroidAutoEntity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/AndroidAutoEntity.cpp.o
.PHONY : src/autoapp/Service/AndroidAutoEntity.cpp.o

src/autoapp/Service/AndroidAutoEntity.i: src/autoapp/Service/AndroidAutoEntity.cpp.i
.PHONY : src/autoapp/Service/AndroidAutoEntity.i

# target to preprocess a source file
src/autoapp/Service/AndroidAutoEntity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/AndroidAutoEntity.cpp.i
.PHONY : src/autoapp/Service/AndroidAutoEntity.cpp.i

src/autoapp/Service/AndroidAutoEntity.s: src/autoapp/Service/AndroidAutoEntity.cpp.s
.PHONY : src/autoapp/Service/AndroidAutoEntity.s

# target to generate assembly for a file
src/autoapp/Service/AndroidAutoEntity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/AndroidAutoEntity.cpp.s
.PHONY : src/autoapp/Service/AndroidAutoEntity.cpp.s

src/autoapp/Service/AndroidAutoEntityFactory.o: src/autoapp/Service/AndroidAutoEntityFactory.cpp.o
.PHONY : src/autoapp/Service/AndroidAutoEntityFactory.o

# target to build an object file
src/autoapp/Service/AndroidAutoEntityFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/AndroidAutoEntityFactory.cpp.o
.PHONY : src/autoapp/Service/AndroidAutoEntityFactory.cpp.o

src/autoapp/Service/AndroidAutoEntityFactory.i: src/autoapp/Service/AndroidAutoEntityFactory.cpp.i
.PHONY : src/autoapp/Service/AndroidAutoEntityFactory.i

# target to preprocess a source file
src/autoapp/Service/AndroidAutoEntityFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/AndroidAutoEntityFactory.cpp.i
.PHONY : src/autoapp/Service/AndroidAutoEntityFactory.cpp.i

src/autoapp/Service/AndroidAutoEntityFactory.s: src/autoapp/Service/AndroidAutoEntityFactory.cpp.s
.PHONY : src/autoapp/Service/AndroidAutoEntityFactory.s

# target to generate assembly for a file
src/autoapp/Service/AndroidAutoEntityFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/AndroidAutoEntityFactory.cpp.s
.PHONY : src/autoapp/Service/AndroidAutoEntityFactory.cpp.s

src/autoapp/Service/Bluetooth/BluetoothService.o: src/autoapp/Service/Bluetooth/BluetoothService.cpp.o
.PHONY : src/autoapp/Service/Bluetooth/BluetoothService.o

# target to build an object file
src/autoapp/Service/Bluetooth/BluetoothService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/Bluetooth/BluetoothService.cpp.o
.PHONY : src/autoapp/Service/Bluetooth/BluetoothService.cpp.o

src/autoapp/Service/Bluetooth/BluetoothService.i: src/autoapp/Service/Bluetooth/BluetoothService.cpp.i
.PHONY : src/autoapp/Service/Bluetooth/BluetoothService.i

# target to preprocess a source file
src/autoapp/Service/Bluetooth/BluetoothService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/Bluetooth/BluetoothService.cpp.i
.PHONY : src/autoapp/Service/Bluetooth/BluetoothService.cpp.i

src/autoapp/Service/Bluetooth/BluetoothService.s: src/autoapp/Service/Bluetooth/BluetoothService.cpp.s
.PHONY : src/autoapp/Service/Bluetooth/BluetoothService.s

# target to generate assembly for a file
src/autoapp/Service/Bluetooth/BluetoothService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/Bluetooth/BluetoothService.cpp.s
.PHONY : src/autoapp/Service/Bluetooth/BluetoothService.cpp.s

src/autoapp/Service/GenericNotification/GenericNotificationService.o: src/autoapp/Service/GenericNotification/GenericNotificationService.cpp.o
.PHONY : src/autoapp/Service/GenericNotification/GenericNotificationService.o

# target to build an object file
src/autoapp/Service/GenericNotification/GenericNotificationService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/GenericNotification/GenericNotificationService.cpp.o
.PHONY : src/autoapp/Service/GenericNotification/GenericNotificationService.cpp.o

src/autoapp/Service/GenericNotification/GenericNotificationService.i: src/autoapp/Service/GenericNotification/GenericNotificationService.cpp.i
.PHONY : src/autoapp/Service/GenericNotification/GenericNotificationService.i

# target to preprocess a source file
src/autoapp/Service/GenericNotification/GenericNotificationService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/GenericNotification/GenericNotificationService.cpp.i
.PHONY : src/autoapp/Service/GenericNotification/GenericNotificationService.cpp.i

src/autoapp/Service/GenericNotification/GenericNotificationService.s: src/autoapp/Service/GenericNotification/GenericNotificationService.cpp.s
.PHONY : src/autoapp/Service/GenericNotification/GenericNotificationService.s

# target to generate assembly for a file
src/autoapp/Service/GenericNotification/GenericNotificationService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/GenericNotification/GenericNotificationService.cpp.s
.PHONY : src/autoapp/Service/GenericNotification/GenericNotificationService.cpp.s

src/autoapp/Service/InputSource/InputSourceService.o: src/autoapp/Service/InputSource/InputSourceService.cpp.o
.PHONY : src/autoapp/Service/InputSource/InputSourceService.o

# target to build an object file
src/autoapp/Service/InputSource/InputSourceService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/InputSource/InputSourceService.cpp.o
.PHONY : src/autoapp/Service/InputSource/InputSourceService.cpp.o

src/autoapp/Service/InputSource/InputSourceService.i: src/autoapp/Service/InputSource/InputSourceService.cpp.i
.PHONY : src/autoapp/Service/InputSource/InputSourceService.i

# target to preprocess a source file
src/autoapp/Service/InputSource/InputSourceService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/InputSource/InputSourceService.cpp.i
.PHONY : src/autoapp/Service/InputSource/InputSourceService.cpp.i

src/autoapp/Service/InputSource/InputSourceService.s: src/autoapp/Service/InputSource/InputSourceService.cpp.s
.PHONY : src/autoapp/Service/InputSource/InputSourceService.s

# target to generate assembly for a file
src/autoapp/Service/InputSource/InputSourceService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/InputSource/InputSourceService.cpp.s
.PHONY : src/autoapp/Service/InputSource/InputSourceService.cpp.s

src/autoapp/Service/MediaBrowser/MediaBrowserService.o: src/autoapp/Service/MediaBrowser/MediaBrowserService.cpp.o
.PHONY : src/autoapp/Service/MediaBrowser/MediaBrowserService.o

# target to build an object file
src/autoapp/Service/MediaBrowser/MediaBrowserService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaBrowser/MediaBrowserService.cpp.o
.PHONY : src/autoapp/Service/MediaBrowser/MediaBrowserService.cpp.o

src/autoapp/Service/MediaBrowser/MediaBrowserService.i: src/autoapp/Service/MediaBrowser/MediaBrowserService.cpp.i
.PHONY : src/autoapp/Service/MediaBrowser/MediaBrowserService.i

# target to preprocess a source file
src/autoapp/Service/MediaBrowser/MediaBrowserService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaBrowser/MediaBrowserService.cpp.i
.PHONY : src/autoapp/Service/MediaBrowser/MediaBrowserService.cpp.i

src/autoapp/Service/MediaBrowser/MediaBrowserService.s: src/autoapp/Service/MediaBrowser/MediaBrowserService.cpp.s
.PHONY : src/autoapp/Service/MediaBrowser/MediaBrowserService.s

# target to generate assembly for a file
src/autoapp/Service/MediaBrowser/MediaBrowserService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaBrowser/MediaBrowserService.cpp.s
.PHONY : src/autoapp/Service/MediaBrowser/MediaBrowserService.cpp.s

src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.o: src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.cpp.o
.PHONY : src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.o

# target to build an object file
src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.cpp.o
.PHONY : src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.cpp.o

src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.i: src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.cpp.i
.PHONY : src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.i

# target to preprocess a source file
src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.cpp.i
.PHONY : src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.cpp.i

src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.s: src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.cpp.s
.PHONY : src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.s

# target to generate assembly for a file
src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.cpp.s
.PHONY : src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.cpp.s

src/autoapp/Service/MediaSink/AudioMediaSinkService.o: src/autoapp/Service/MediaSink/AudioMediaSinkService.cpp.o
.PHONY : src/autoapp/Service/MediaSink/AudioMediaSinkService.o

# target to build an object file
src/autoapp/Service/MediaSink/AudioMediaSinkService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/AudioMediaSinkService.cpp.o
.PHONY : src/autoapp/Service/MediaSink/AudioMediaSinkService.cpp.o

src/autoapp/Service/MediaSink/AudioMediaSinkService.i: src/autoapp/Service/MediaSink/AudioMediaSinkService.cpp.i
.PHONY : src/autoapp/Service/MediaSink/AudioMediaSinkService.i

# target to preprocess a source file
src/autoapp/Service/MediaSink/AudioMediaSinkService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/AudioMediaSinkService.cpp.i
.PHONY : src/autoapp/Service/MediaSink/AudioMediaSinkService.cpp.i

src/autoapp/Service/MediaSink/AudioMediaSinkService.s: src/autoapp/Service/MediaSink/AudioMediaSinkService.cpp.s
.PHONY : src/autoapp/Service/MediaSink/AudioMediaSinkService.s

# target to generate assembly for a file
src/autoapp/Service/MediaSink/AudioMediaSinkService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/AudioMediaSinkService.cpp.s
.PHONY : src/autoapp/Service/MediaSink/AudioMediaSinkService.cpp.s

src/autoapp/Service/MediaSink/GuidanceAudioService.o: src/autoapp/Service/MediaSink/GuidanceAudioService.cpp.o
.PHONY : src/autoapp/Service/MediaSink/GuidanceAudioService.o

# target to build an object file
src/autoapp/Service/MediaSink/GuidanceAudioService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/GuidanceAudioService.cpp.o
.PHONY : src/autoapp/Service/MediaSink/GuidanceAudioService.cpp.o

src/autoapp/Service/MediaSink/GuidanceAudioService.i: src/autoapp/Service/MediaSink/GuidanceAudioService.cpp.i
.PHONY : src/autoapp/Service/MediaSink/GuidanceAudioService.i

# target to preprocess a source file
src/autoapp/Service/MediaSink/GuidanceAudioService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/GuidanceAudioService.cpp.i
.PHONY : src/autoapp/Service/MediaSink/GuidanceAudioService.cpp.i

src/autoapp/Service/MediaSink/GuidanceAudioService.s: src/autoapp/Service/MediaSink/GuidanceAudioService.cpp.s
.PHONY : src/autoapp/Service/MediaSink/GuidanceAudioService.s

# target to generate assembly for a file
src/autoapp/Service/MediaSink/GuidanceAudioService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/GuidanceAudioService.cpp.s
.PHONY : src/autoapp/Service/MediaSink/GuidanceAudioService.cpp.s

src/autoapp/Service/MediaSink/MediaAudioService.o: src/autoapp/Service/MediaSink/MediaAudioService.cpp.o
.PHONY : src/autoapp/Service/MediaSink/MediaAudioService.o

# target to build an object file
src/autoapp/Service/MediaSink/MediaAudioService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/MediaAudioService.cpp.o
.PHONY : src/autoapp/Service/MediaSink/MediaAudioService.cpp.o

src/autoapp/Service/MediaSink/MediaAudioService.i: src/autoapp/Service/MediaSink/MediaAudioService.cpp.i
.PHONY : src/autoapp/Service/MediaSink/MediaAudioService.i

# target to preprocess a source file
src/autoapp/Service/MediaSink/MediaAudioService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/MediaAudioService.cpp.i
.PHONY : src/autoapp/Service/MediaSink/MediaAudioService.cpp.i

src/autoapp/Service/MediaSink/MediaAudioService.s: src/autoapp/Service/MediaSink/MediaAudioService.cpp.s
.PHONY : src/autoapp/Service/MediaSink/MediaAudioService.s

# target to generate assembly for a file
src/autoapp/Service/MediaSink/MediaAudioService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/MediaAudioService.cpp.s
.PHONY : src/autoapp/Service/MediaSink/MediaAudioService.cpp.s

src/autoapp/Service/MediaSink/SystemAudioService.o: src/autoapp/Service/MediaSink/SystemAudioService.cpp.o
.PHONY : src/autoapp/Service/MediaSink/SystemAudioService.o

# target to build an object file
src/autoapp/Service/MediaSink/SystemAudioService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/SystemAudioService.cpp.o
.PHONY : src/autoapp/Service/MediaSink/SystemAudioService.cpp.o

src/autoapp/Service/MediaSink/SystemAudioService.i: src/autoapp/Service/MediaSink/SystemAudioService.cpp.i
.PHONY : src/autoapp/Service/MediaSink/SystemAudioService.i

# target to preprocess a source file
src/autoapp/Service/MediaSink/SystemAudioService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/SystemAudioService.cpp.i
.PHONY : src/autoapp/Service/MediaSink/SystemAudioService.cpp.i

src/autoapp/Service/MediaSink/SystemAudioService.s: src/autoapp/Service/MediaSink/SystemAudioService.cpp.s
.PHONY : src/autoapp/Service/MediaSink/SystemAudioService.s

# target to generate assembly for a file
src/autoapp/Service/MediaSink/SystemAudioService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/SystemAudioService.cpp.s
.PHONY : src/autoapp/Service/MediaSink/SystemAudioService.cpp.s

src/autoapp/Service/MediaSink/TelephonyAudioService.o: src/autoapp/Service/MediaSink/TelephonyAudioService.cpp.o
.PHONY : src/autoapp/Service/MediaSink/TelephonyAudioService.o

# target to build an object file
src/autoapp/Service/MediaSink/TelephonyAudioService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/TelephonyAudioService.cpp.o
.PHONY : src/autoapp/Service/MediaSink/TelephonyAudioService.cpp.o

src/autoapp/Service/MediaSink/TelephonyAudioService.i: src/autoapp/Service/MediaSink/TelephonyAudioService.cpp.i
.PHONY : src/autoapp/Service/MediaSink/TelephonyAudioService.i

# target to preprocess a source file
src/autoapp/Service/MediaSink/TelephonyAudioService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/TelephonyAudioService.cpp.i
.PHONY : src/autoapp/Service/MediaSink/TelephonyAudioService.cpp.i

src/autoapp/Service/MediaSink/TelephonyAudioService.s: src/autoapp/Service/MediaSink/TelephonyAudioService.cpp.s
.PHONY : src/autoapp/Service/MediaSink/TelephonyAudioService.s

# target to generate assembly for a file
src/autoapp/Service/MediaSink/TelephonyAudioService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/TelephonyAudioService.cpp.s
.PHONY : src/autoapp/Service/MediaSink/TelephonyAudioService.cpp.s

src/autoapp/Service/MediaSink/VideoMediaSinkService.o: src/autoapp/Service/MediaSink/VideoMediaSinkService.cpp.o
.PHONY : src/autoapp/Service/MediaSink/VideoMediaSinkService.o

# target to build an object file
src/autoapp/Service/MediaSink/VideoMediaSinkService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/VideoMediaSinkService.cpp.o
.PHONY : src/autoapp/Service/MediaSink/VideoMediaSinkService.cpp.o

src/autoapp/Service/MediaSink/VideoMediaSinkService.i: src/autoapp/Service/MediaSink/VideoMediaSinkService.cpp.i
.PHONY : src/autoapp/Service/MediaSink/VideoMediaSinkService.i

# target to preprocess a source file
src/autoapp/Service/MediaSink/VideoMediaSinkService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/VideoMediaSinkService.cpp.i
.PHONY : src/autoapp/Service/MediaSink/VideoMediaSinkService.cpp.i

src/autoapp/Service/MediaSink/VideoMediaSinkService.s: src/autoapp/Service/MediaSink/VideoMediaSinkService.cpp.s
.PHONY : src/autoapp/Service/MediaSink/VideoMediaSinkService.s

# target to generate assembly for a file
src/autoapp/Service/MediaSink/VideoMediaSinkService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/VideoMediaSinkService.cpp.s
.PHONY : src/autoapp/Service/MediaSink/VideoMediaSinkService.cpp.s

src/autoapp/Service/MediaSink/VideoService.o: src/autoapp/Service/MediaSink/VideoService.cpp.o
.PHONY : src/autoapp/Service/MediaSink/VideoService.o

# target to build an object file
src/autoapp/Service/MediaSink/VideoService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/VideoService.cpp.o
.PHONY : src/autoapp/Service/MediaSink/VideoService.cpp.o

src/autoapp/Service/MediaSink/VideoService.i: src/autoapp/Service/MediaSink/VideoService.cpp.i
.PHONY : src/autoapp/Service/MediaSink/VideoService.i

# target to preprocess a source file
src/autoapp/Service/MediaSink/VideoService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/VideoService.cpp.i
.PHONY : src/autoapp/Service/MediaSink/VideoService.cpp.i

src/autoapp/Service/MediaSink/VideoService.s: src/autoapp/Service/MediaSink/VideoService.cpp.s
.PHONY : src/autoapp/Service/MediaSink/VideoService.s

# target to generate assembly for a file
src/autoapp/Service/MediaSink/VideoService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSink/VideoService.cpp.s
.PHONY : src/autoapp/Service/MediaSink/VideoService.cpp.s

src/autoapp/Service/MediaSource/MediaSourceService.o: src/autoapp/Service/MediaSource/MediaSourceService.cpp.o
.PHONY : src/autoapp/Service/MediaSource/MediaSourceService.o

# target to build an object file
src/autoapp/Service/MediaSource/MediaSourceService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSource/MediaSourceService.cpp.o
.PHONY : src/autoapp/Service/MediaSource/MediaSourceService.cpp.o

src/autoapp/Service/MediaSource/MediaSourceService.i: src/autoapp/Service/MediaSource/MediaSourceService.cpp.i
.PHONY : src/autoapp/Service/MediaSource/MediaSourceService.i

# target to preprocess a source file
src/autoapp/Service/MediaSource/MediaSourceService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSource/MediaSourceService.cpp.i
.PHONY : src/autoapp/Service/MediaSource/MediaSourceService.cpp.i

src/autoapp/Service/MediaSource/MediaSourceService.s: src/autoapp/Service/MediaSource/MediaSourceService.cpp.s
.PHONY : src/autoapp/Service/MediaSource/MediaSourceService.s

# target to generate assembly for a file
src/autoapp/Service/MediaSource/MediaSourceService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSource/MediaSourceService.cpp.s
.PHONY : src/autoapp/Service/MediaSource/MediaSourceService.cpp.s

src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.o: src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.cpp.o
.PHONY : src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.o

# target to build an object file
src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.cpp.o
.PHONY : src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.cpp.o

src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.i: src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.cpp.i
.PHONY : src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.i

# target to preprocess a source file
src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.cpp.i
.PHONY : src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.cpp.i

src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.s: src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.cpp.s
.PHONY : src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.s

# target to generate assembly for a file
src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.cpp.s
.PHONY : src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.cpp.s

src/autoapp/Service/NavigationStatus/NavigationStatusService.o: src/autoapp/Service/NavigationStatus/NavigationStatusService.cpp.o
.PHONY : src/autoapp/Service/NavigationStatus/NavigationStatusService.o

# target to build an object file
src/autoapp/Service/NavigationStatus/NavigationStatusService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/NavigationStatus/NavigationStatusService.cpp.o
.PHONY : src/autoapp/Service/NavigationStatus/NavigationStatusService.cpp.o

src/autoapp/Service/NavigationStatus/NavigationStatusService.i: src/autoapp/Service/NavigationStatus/NavigationStatusService.cpp.i
.PHONY : src/autoapp/Service/NavigationStatus/NavigationStatusService.i

# target to preprocess a source file
src/autoapp/Service/NavigationStatus/NavigationStatusService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/NavigationStatus/NavigationStatusService.cpp.i
.PHONY : src/autoapp/Service/NavigationStatus/NavigationStatusService.cpp.i

src/autoapp/Service/NavigationStatus/NavigationStatusService.s: src/autoapp/Service/NavigationStatus/NavigationStatusService.cpp.s
.PHONY : src/autoapp/Service/NavigationStatus/NavigationStatusService.s

# target to generate assembly for a file
src/autoapp/Service/NavigationStatus/NavigationStatusService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/NavigationStatus/NavigationStatusService.cpp.s
.PHONY : src/autoapp/Service/NavigationStatus/NavigationStatusService.cpp.s

src/autoapp/Service/PhoneStatus/PhoneStatusService.o: src/autoapp/Service/PhoneStatus/PhoneStatusService.cpp.o
.PHONY : src/autoapp/Service/PhoneStatus/PhoneStatusService.o

# target to build an object file
src/autoapp/Service/PhoneStatus/PhoneStatusService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/PhoneStatus/PhoneStatusService.cpp.o
.PHONY : src/autoapp/Service/PhoneStatus/PhoneStatusService.cpp.o

src/autoapp/Service/PhoneStatus/PhoneStatusService.i: src/autoapp/Service/PhoneStatus/PhoneStatusService.cpp.i
.PHONY : src/autoapp/Service/PhoneStatus/PhoneStatusService.i

# target to preprocess a source file
src/autoapp/Service/PhoneStatus/PhoneStatusService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/PhoneStatus/PhoneStatusService.cpp.i
.PHONY : src/autoapp/Service/PhoneStatus/PhoneStatusService.cpp.i

src/autoapp/Service/PhoneStatus/PhoneStatusService.s: src/autoapp/Service/PhoneStatus/PhoneStatusService.cpp.s
.PHONY : src/autoapp/Service/PhoneStatus/PhoneStatusService.s

# target to generate assembly for a file
src/autoapp/Service/PhoneStatus/PhoneStatusService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/PhoneStatus/PhoneStatusService.cpp.s
.PHONY : src/autoapp/Service/PhoneStatus/PhoneStatusService.cpp.s

src/autoapp/Service/Pinger.o: src/autoapp/Service/Pinger.cpp.o
.PHONY : src/autoapp/Service/Pinger.o

# target to build an object file
src/autoapp/Service/Pinger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/Pinger.cpp.o
.PHONY : src/autoapp/Service/Pinger.cpp.o

src/autoapp/Service/Pinger.i: src/autoapp/Service/Pinger.cpp.i
.PHONY : src/autoapp/Service/Pinger.i

# target to preprocess a source file
src/autoapp/Service/Pinger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/Pinger.cpp.i
.PHONY : src/autoapp/Service/Pinger.cpp.i

src/autoapp/Service/Pinger.s: src/autoapp/Service/Pinger.cpp.s
.PHONY : src/autoapp/Service/Pinger.s

# target to generate assembly for a file
src/autoapp/Service/Pinger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/Pinger.cpp.s
.PHONY : src/autoapp/Service/Pinger.cpp.s

src/autoapp/Service/Radio/RadioService.o: src/autoapp/Service/Radio/RadioService.cpp.o
.PHONY : src/autoapp/Service/Radio/RadioService.o

# target to build an object file
src/autoapp/Service/Radio/RadioService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/Radio/RadioService.cpp.o
.PHONY : src/autoapp/Service/Radio/RadioService.cpp.o

src/autoapp/Service/Radio/RadioService.i: src/autoapp/Service/Radio/RadioService.cpp.i
.PHONY : src/autoapp/Service/Radio/RadioService.i

# target to preprocess a source file
src/autoapp/Service/Radio/RadioService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/Radio/RadioService.cpp.i
.PHONY : src/autoapp/Service/Radio/RadioService.cpp.i

src/autoapp/Service/Radio/RadioService.s: src/autoapp/Service/Radio/RadioService.cpp.s
.PHONY : src/autoapp/Service/Radio/RadioService.s

# target to generate assembly for a file
src/autoapp/Service/Radio/RadioService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/Radio/RadioService.cpp.s
.PHONY : src/autoapp/Service/Radio/RadioService.cpp.s

src/autoapp/Service/Sensor/SensorService.o: src/autoapp/Service/Sensor/SensorService.cpp.o
.PHONY : src/autoapp/Service/Sensor/SensorService.o

# target to build an object file
src/autoapp/Service/Sensor/SensorService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/Sensor/SensorService.cpp.o
.PHONY : src/autoapp/Service/Sensor/SensorService.cpp.o

src/autoapp/Service/Sensor/SensorService.i: src/autoapp/Service/Sensor/SensorService.cpp.i
.PHONY : src/autoapp/Service/Sensor/SensorService.i

# target to preprocess a source file
src/autoapp/Service/Sensor/SensorService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/Sensor/SensorService.cpp.i
.PHONY : src/autoapp/Service/Sensor/SensorService.cpp.i

src/autoapp/Service/Sensor/SensorService.s: src/autoapp/Service/Sensor/SensorService.cpp.s
.PHONY : src/autoapp/Service/Sensor/SensorService.s

# target to generate assembly for a file
src/autoapp/Service/Sensor/SensorService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/Sensor/SensorService.cpp.s
.PHONY : src/autoapp/Service/Sensor/SensorService.cpp.s

src/autoapp/Service/ServiceFactory.o: src/autoapp/Service/ServiceFactory.cpp.o
.PHONY : src/autoapp/Service/ServiceFactory.o

# target to build an object file
src/autoapp/Service/ServiceFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/ServiceFactory.cpp.o
.PHONY : src/autoapp/Service/ServiceFactory.cpp.o

src/autoapp/Service/ServiceFactory.i: src/autoapp/Service/ServiceFactory.cpp.i
.PHONY : src/autoapp/Service/ServiceFactory.i

# target to preprocess a source file
src/autoapp/Service/ServiceFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/ServiceFactory.cpp.i
.PHONY : src/autoapp/Service/ServiceFactory.cpp.i

src/autoapp/Service/ServiceFactory.s: src/autoapp/Service/ServiceFactory.cpp.s
.PHONY : src/autoapp/Service/ServiceFactory.s

# target to generate assembly for a file
src/autoapp/Service/ServiceFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/ServiceFactory.cpp.s
.PHONY : src/autoapp/Service/ServiceFactory.cpp.s

src/autoapp/Service/VendorExtension/VendorExtensionService.o: src/autoapp/Service/VendorExtension/VendorExtensionService.cpp.o
.PHONY : src/autoapp/Service/VendorExtension/VendorExtensionService.o

# target to build an object file
src/autoapp/Service/VendorExtension/VendorExtensionService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/VendorExtension/VendorExtensionService.cpp.o
.PHONY : src/autoapp/Service/VendorExtension/VendorExtensionService.cpp.o

src/autoapp/Service/VendorExtension/VendorExtensionService.i: src/autoapp/Service/VendorExtension/VendorExtensionService.cpp.i
.PHONY : src/autoapp/Service/VendorExtension/VendorExtensionService.i

# target to preprocess a source file
src/autoapp/Service/VendorExtension/VendorExtensionService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/VendorExtension/VendorExtensionService.cpp.i
.PHONY : src/autoapp/Service/VendorExtension/VendorExtensionService.cpp.i

src/autoapp/Service/VendorExtension/VendorExtensionService.s: src/autoapp/Service/VendorExtension/VendorExtensionService.cpp.s
.PHONY : src/autoapp/Service/VendorExtension/VendorExtensionService.s

# target to generate assembly for a file
src/autoapp/Service/VendorExtension/VendorExtensionService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/VendorExtension/VendorExtensionService.cpp.s
.PHONY : src/autoapp/Service/VendorExtension/VendorExtensionService.cpp.s

src/autoapp/Service/WifiProjection/WifiProjectionService.o: src/autoapp/Service/WifiProjection/WifiProjectionService.cpp.o
.PHONY : src/autoapp/Service/WifiProjection/WifiProjectionService.o

# target to build an object file
src/autoapp/Service/WifiProjection/WifiProjectionService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/WifiProjection/WifiProjectionService.cpp.o
.PHONY : src/autoapp/Service/WifiProjection/WifiProjectionService.cpp.o

src/autoapp/Service/WifiProjection/WifiProjectionService.i: src/autoapp/Service/WifiProjection/WifiProjectionService.cpp.i
.PHONY : src/autoapp/Service/WifiProjection/WifiProjectionService.i

# target to preprocess a source file
src/autoapp/Service/WifiProjection/WifiProjectionService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/WifiProjection/WifiProjectionService.cpp.i
.PHONY : src/autoapp/Service/WifiProjection/WifiProjectionService.cpp.i

src/autoapp/Service/WifiProjection/WifiProjectionService.s: src/autoapp/Service/WifiProjection/WifiProjectionService.cpp.s
.PHONY : src/autoapp/Service/WifiProjection/WifiProjectionService.s

# target to generate assembly for a file
src/autoapp/Service/WifiProjection/WifiProjectionService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/Service/WifiProjection/WifiProjectionService.cpp.s
.PHONY : src/autoapp/Service/WifiProjection/WifiProjectionService.cpp.s

src/autoapp/UI/ConnectDialog.o: src/autoapp/UI/ConnectDialog.cpp.o
.PHONY : src/autoapp/UI/ConnectDialog.o

# target to build an object file
src/autoapp/UI/ConnectDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/ConnectDialog.cpp.o
.PHONY : src/autoapp/UI/ConnectDialog.cpp.o

src/autoapp/UI/ConnectDialog.i: src/autoapp/UI/ConnectDialog.cpp.i
.PHONY : src/autoapp/UI/ConnectDialog.i

# target to preprocess a source file
src/autoapp/UI/ConnectDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/ConnectDialog.cpp.i
.PHONY : src/autoapp/UI/ConnectDialog.cpp.i

src/autoapp/UI/ConnectDialog.s: src/autoapp/UI/ConnectDialog.cpp.s
.PHONY : src/autoapp/UI/ConnectDialog.s

# target to generate assembly for a file
src/autoapp/UI/ConnectDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/ConnectDialog.cpp.s
.PHONY : src/autoapp/UI/ConnectDialog.cpp.s

src/autoapp/UI/MainWindow.o: src/autoapp/UI/MainWindow.cpp.o
.PHONY : src/autoapp/UI/MainWindow.o

# target to build an object file
src/autoapp/UI/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/MainWindow.cpp.o
.PHONY : src/autoapp/UI/MainWindow.cpp.o

src/autoapp/UI/MainWindow.i: src/autoapp/UI/MainWindow.cpp.i
.PHONY : src/autoapp/UI/MainWindow.i

# target to preprocess a source file
src/autoapp/UI/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/MainWindow.cpp.i
.PHONY : src/autoapp/UI/MainWindow.cpp.i

src/autoapp/UI/MainWindow.s: src/autoapp/UI/MainWindow.cpp.s
.PHONY : src/autoapp/UI/MainWindow.s

# target to generate assembly for a file
src/autoapp/UI/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/MainWindow.cpp.s
.PHONY : src/autoapp/UI/MainWindow.cpp.s

src/autoapp/UI/SettingsWindow.o: src/autoapp/UI/SettingsWindow.cpp.o
.PHONY : src/autoapp/UI/SettingsWindow.o

# target to build an object file
src/autoapp/UI/SettingsWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/SettingsWindow.cpp.o
.PHONY : src/autoapp/UI/SettingsWindow.cpp.o

src/autoapp/UI/SettingsWindow.i: src/autoapp/UI/SettingsWindow.cpp.i
.PHONY : src/autoapp/UI/SettingsWindow.i

# target to preprocess a source file
src/autoapp/UI/SettingsWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/SettingsWindow.cpp.i
.PHONY : src/autoapp/UI/SettingsWindow.cpp.i

src/autoapp/UI/SettingsWindow.s: src/autoapp/UI/SettingsWindow.cpp.s
.PHONY : src/autoapp/UI/SettingsWindow.s

# target to generate assembly for a file
src/autoapp/UI/SettingsWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/SettingsWindow.cpp.s
.PHONY : src/autoapp/UI/SettingsWindow.cpp.s

src/autoapp/UI/UpdateDialog.o: src/autoapp/UI/UpdateDialog.cpp.o
.PHONY : src/autoapp/UI/UpdateDialog.o

# target to build an object file
src/autoapp/UI/UpdateDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/UpdateDialog.cpp.o
.PHONY : src/autoapp/UI/UpdateDialog.cpp.o

src/autoapp/UI/UpdateDialog.i: src/autoapp/UI/UpdateDialog.cpp.i
.PHONY : src/autoapp/UI/UpdateDialog.i

# target to preprocess a source file
src/autoapp/UI/UpdateDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/UpdateDialog.cpp.i
.PHONY : src/autoapp/UI/UpdateDialog.cpp.i

src/autoapp/UI/UpdateDialog.s: src/autoapp/UI/UpdateDialog.cpp.s
.PHONY : src/autoapp/UI/UpdateDialog.s

# target to generate assembly for a file
src/autoapp/UI/UpdateDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/UpdateDialog.cpp.s
.PHONY : src/autoapp/UI/UpdateDialog.cpp.s

src/autoapp/UI/WarningDialog.o: src/autoapp/UI/WarningDialog.cpp.o
.PHONY : src/autoapp/UI/WarningDialog.o

# target to build an object file
src/autoapp/UI/WarningDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/WarningDialog.cpp.o
.PHONY : src/autoapp/UI/WarningDialog.cpp.o

src/autoapp/UI/WarningDialog.i: src/autoapp/UI/WarningDialog.cpp.i
.PHONY : src/autoapp/UI/WarningDialog.i

# target to preprocess a source file
src/autoapp/UI/WarningDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/WarningDialog.cpp.i
.PHONY : src/autoapp/UI/WarningDialog.cpp.i

src/autoapp/UI/WarningDialog.s: src/autoapp/UI/WarningDialog.cpp.s
.PHONY : src/autoapp/UI/WarningDialog.s

# target to generate assembly for a file
src/autoapp/UI/WarningDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/WarningDialog.cpp.s
.PHONY : src/autoapp/UI/WarningDialog.cpp.s

src/autoapp/UI/dialog.o: src/autoapp/UI/dialog.cpp.o
.PHONY : src/autoapp/UI/dialog.o

# target to build an object file
src/autoapp/UI/dialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/dialog.cpp.o
.PHONY : src/autoapp/UI/dialog.cpp.o

src/autoapp/UI/dialog.i: src/autoapp/UI/dialog.cpp.i
.PHONY : src/autoapp/UI/dialog.i

# target to preprocess a source file
src/autoapp/UI/dialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/dialog.cpp.i
.PHONY : src/autoapp/UI/dialog.cpp.i

src/autoapp/UI/dialog.s: src/autoapp/UI/dialog.cpp.s
.PHONY : src/autoapp/UI/dialog.s

# target to generate assembly for a file
src/autoapp/UI/dialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/UI/dialog.cpp.s
.PHONY : src/autoapp/UI/dialog.cpp.s

src/autoapp/autoapp.o: src/autoapp/autoapp.cpp.o
.PHONY : src/autoapp/autoapp.o

# target to build an object file
src/autoapp/autoapp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/autoapp.cpp.o
.PHONY : src/autoapp/autoapp.cpp.o

src/autoapp/autoapp.i: src/autoapp/autoapp.cpp.i
.PHONY : src/autoapp/autoapp.i

# target to preprocess a source file
src/autoapp/autoapp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/autoapp.cpp.i
.PHONY : src/autoapp/autoapp.cpp.i

src/autoapp/autoapp.s: src/autoapp/autoapp.cpp.s
.PHONY : src/autoapp/autoapp.s

# target to generate assembly for a file
src/autoapp/autoapp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/autoapp.dir/build.make CMakeFiles/autoapp.dir/src/autoapp/autoapp.cpp.s
.PHONY : src/autoapp/autoapp.cpp.s

src/btservice/AndroidBluetoothServer.o: src/btservice/AndroidBluetoothServer.cpp.o
.PHONY : src/btservice/AndroidBluetoothServer.o

# target to build an object file
src/btservice/AndroidBluetoothServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/btservice/AndroidBluetoothServer.cpp.o
.PHONY : src/btservice/AndroidBluetoothServer.cpp.o

src/btservice/AndroidBluetoothServer.i: src/btservice/AndroidBluetoothServer.cpp.i
.PHONY : src/btservice/AndroidBluetoothServer.i

# target to preprocess a source file
src/btservice/AndroidBluetoothServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/btservice/AndroidBluetoothServer.cpp.i
.PHONY : src/btservice/AndroidBluetoothServer.cpp.i

src/btservice/AndroidBluetoothServer.s: src/btservice/AndroidBluetoothServer.cpp.s
.PHONY : src/btservice/AndroidBluetoothServer.s

# target to generate assembly for a file
src/btservice/AndroidBluetoothServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/btservice/AndroidBluetoothServer.cpp.s
.PHONY : src/btservice/AndroidBluetoothServer.cpp.s

src/btservice/AndroidBluetoothService.o: src/btservice/AndroidBluetoothService.cpp.o
.PHONY : src/btservice/AndroidBluetoothService.o

# target to build an object file
src/btservice/AndroidBluetoothService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/btservice/AndroidBluetoothService.cpp.o
.PHONY : src/btservice/AndroidBluetoothService.cpp.o

src/btservice/AndroidBluetoothService.i: src/btservice/AndroidBluetoothService.cpp.i
.PHONY : src/btservice/AndroidBluetoothService.i

# target to preprocess a source file
src/btservice/AndroidBluetoothService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/btservice/AndroidBluetoothService.cpp.i
.PHONY : src/btservice/AndroidBluetoothService.cpp.i

src/btservice/AndroidBluetoothService.s: src/btservice/AndroidBluetoothService.cpp.s
.PHONY : src/btservice/AndroidBluetoothService.s

# target to generate assembly for a file
src/btservice/AndroidBluetoothService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/btservice/AndroidBluetoothService.cpp.s
.PHONY : src/btservice/AndroidBluetoothService.cpp.s

src/btservice/BluetoothHandler.o: src/btservice/BluetoothHandler.cpp.o
.PHONY : src/btservice/BluetoothHandler.o

# target to build an object file
src/btservice/BluetoothHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/btservice/BluetoothHandler.cpp.o
.PHONY : src/btservice/BluetoothHandler.cpp.o

src/btservice/BluetoothHandler.i: src/btservice/BluetoothHandler.cpp.i
.PHONY : src/btservice/BluetoothHandler.i

# target to preprocess a source file
src/btservice/BluetoothHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/btservice/BluetoothHandler.cpp.i
.PHONY : src/btservice/BluetoothHandler.cpp.i

src/btservice/BluetoothHandler.s: src/btservice/BluetoothHandler.cpp.s
.PHONY : src/btservice/BluetoothHandler.s

# target to generate assembly for a file
src/btservice/BluetoothHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/btservice/BluetoothHandler.cpp.s
.PHONY : src/btservice/BluetoothHandler.cpp.s

src/btservice/btservice.o: src/btservice/btservice.cpp.o
.PHONY : src/btservice/btservice.o

# target to build an object file
src/btservice/btservice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/btservice/btservice.cpp.o
.PHONY : src/btservice/btservice.cpp.o

src/btservice/btservice.i: src/btservice/btservice.cpp.i
.PHONY : src/btservice/btservice.i

# target to preprocess a source file
src/btservice/btservice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/btservice/btservice.cpp.i
.PHONY : src/btservice/btservice.cpp.i

src/btservice/btservice.s: src/btservice/btservice.cpp.s
.PHONY : src/btservice/btservice.s

# target to generate assembly for a file
src/btservice/btservice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/btservice.dir/build.make CMakeFiles/btservice.dir/src/btservice/btservice.cpp.s
.PHONY : src/btservice/btservice.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... autoapp_autogen"
	@echo "... autoapp_autogen_timestamp_deps"
	@echo "... btservice_autogen"
	@echo "... btservice_autogen_timestamp_deps"
	@echo "... autoapp"
	@echo "... btservice"
	@echo "... autoapp_autogen/GBFAFXFCVO/qrc_resources.o"
	@echo "... autoapp_autogen/GBFAFXFCVO/qrc_resources.i"
	@echo "... autoapp_autogen/GBFAFXFCVO/qrc_resources.s"
	@echo "... autoapp_autogen/mocs_compilation.o"
	@echo "... autoapp_autogen/mocs_compilation.i"
	@echo "... autoapp_autogen/mocs_compilation.s"
	@echo "... btservice_autogen/mocs_compilation.o"
	@echo "... btservice_autogen/mocs_compilation.i"
	@echo "... btservice_autogen/mocs_compilation.s"
	@echo "... src/autoapp/App.o"
	@echo "... src/autoapp/App.i"
	@echo "... src/autoapp/App.s"
	@echo "... src/autoapp/Configuration/Configuration.o"
	@echo "... src/autoapp/Configuration/Configuration.i"
	@echo "... src/autoapp/Configuration/Configuration.s"
	@echo "... src/autoapp/Configuration/RecentAddressesList.o"
	@echo "... src/autoapp/Configuration/RecentAddressesList.i"
	@echo "... src/autoapp/Configuration/RecentAddressesList.s"
	@echo "... src/autoapp/Projection/DummyBluetoothDevice.o"
	@echo "... src/autoapp/Projection/DummyBluetoothDevice.i"
	@echo "... src/autoapp/Projection/DummyBluetoothDevice.s"
	@echo "... src/autoapp/Projection/InputDevice.o"
	@echo "... src/autoapp/Projection/InputDevice.i"
	@echo "... src/autoapp/Projection/InputDevice.s"
	@echo "... src/autoapp/Projection/LocalBluetoothDevice.o"
	@echo "... src/autoapp/Projection/LocalBluetoothDevice.i"
	@echo "... src/autoapp/Projection/LocalBluetoothDevice.s"
	@echo "... src/autoapp/Projection/OMXVideoOutput.o"
	@echo "... src/autoapp/Projection/OMXVideoOutput.i"
	@echo "... src/autoapp/Projection/OMXVideoOutput.s"
	@echo "... src/autoapp/Projection/QtAudioInput.o"
	@echo "... src/autoapp/Projection/QtAudioInput.i"
	@echo "... src/autoapp/Projection/QtAudioInput.s"
	@echo "... src/autoapp/Projection/QtAudioOutput.o"
	@echo "... src/autoapp/Projection/QtAudioOutput.i"
	@echo "... src/autoapp/Projection/QtAudioOutput.s"
	@echo "... src/autoapp/Projection/QtVideoOutput.o"
	@echo "... src/autoapp/Projection/QtVideoOutput.i"
	@echo "... src/autoapp/Projection/QtVideoOutput.s"
	@echo "... src/autoapp/Projection/RtAudioOutput.o"
	@echo "... src/autoapp/Projection/RtAudioOutput.i"
	@echo "... src/autoapp/Projection/RtAudioOutput.s"
	@echo "... src/autoapp/Projection/SequentialBuffer.o"
	@echo "... src/autoapp/Projection/SequentialBuffer.i"
	@echo "... src/autoapp/Projection/SequentialBuffer.s"
	@echo "... src/autoapp/Projection/VideoOutput.o"
	@echo "... src/autoapp/Projection/VideoOutput.i"
	@echo "... src/autoapp/Projection/VideoOutput.s"
	@echo "... src/autoapp/Service/AndroidAutoEntity.o"
	@echo "... src/autoapp/Service/AndroidAutoEntity.i"
	@echo "... src/autoapp/Service/AndroidAutoEntity.s"
	@echo "... src/autoapp/Service/AndroidAutoEntityFactory.o"
	@echo "... src/autoapp/Service/AndroidAutoEntityFactory.i"
	@echo "... src/autoapp/Service/AndroidAutoEntityFactory.s"
	@echo "... src/autoapp/Service/Bluetooth/BluetoothService.o"
	@echo "... src/autoapp/Service/Bluetooth/BluetoothService.i"
	@echo "... src/autoapp/Service/Bluetooth/BluetoothService.s"
	@echo "... src/autoapp/Service/GenericNotification/GenericNotificationService.o"
	@echo "... src/autoapp/Service/GenericNotification/GenericNotificationService.i"
	@echo "... src/autoapp/Service/GenericNotification/GenericNotificationService.s"
	@echo "... src/autoapp/Service/InputSource/InputSourceService.o"
	@echo "... src/autoapp/Service/InputSource/InputSourceService.i"
	@echo "... src/autoapp/Service/InputSource/InputSourceService.s"
	@echo "... src/autoapp/Service/MediaBrowser/MediaBrowserService.o"
	@echo "... src/autoapp/Service/MediaBrowser/MediaBrowserService.i"
	@echo "... src/autoapp/Service/MediaBrowser/MediaBrowserService.s"
	@echo "... src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.o"
	@echo "... src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.i"
	@echo "... src/autoapp/Service/MediaPlaybackStatus/MediaPlaybackStatusService.s"
	@echo "... src/autoapp/Service/MediaSink/AudioMediaSinkService.o"
	@echo "... src/autoapp/Service/MediaSink/AudioMediaSinkService.i"
	@echo "... src/autoapp/Service/MediaSink/AudioMediaSinkService.s"
	@echo "... src/autoapp/Service/MediaSink/GuidanceAudioService.o"
	@echo "... src/autoapp/Service/MediaSink/GuidanceAudioService.i"
	@echo "... src/autoapp/Service/MediaSink/GuidanceAudioService.s"
	@echo "... src/autoapp/Service/MediaSink/MediaAudioService.o"
	@echo "... src/autoapp/Service/MediaSink/MediaAudioService.i"
	@echo "... src/autoapp/Service/MediaSink/MediaAudioService.s"
	@echo "... src/autoapp/Service/MediaSink/SystemAudioService.o"
	@echo "... src/autoapp/Service/MediaSink/SystemAudioService.i"
	@echo "... src/autoapp/Service/MediaSink/SystemAudioService.s"
	@echo "... src/autoapp/Service/MediaSink/TelephonyAudioService.o"
	@echo "... src/autoapp/Service/MediaSink/TelephonyAudioService.i"
	@echo "... src/autoapp/Service/MediaSink/TelephonyAudioService.s"
	@echo "... src/autoapp/Service/MediaSink/VideoMediaSinkService.o"
	@echo "... src/autoapp/Service/MediaSink/VideoMediaSinkService.i"
	@echo "... src/autoapp/Service/MediaSink/VideoMediaSinkService.s"
	@echo "... src/autoapp/Service/MediaSink/VideoService.o"
	@echo "... src/autoapp/Service/MediaSink/VideoService.i"
	@echo "... src/autoapp/Service/MediaSink/VideoService.s"
	@echo "... src/autoapp/Service/MediaSource/MediaSourceService.o"
	@echo "... src/autoapp/Service/MediaSource/MediaSourceService.i"
	@echo "... src/autoapp/Service/MediaSource/MediaSourceService.s"
	@echo "... src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.o"
	@echo "... src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.i"
	@echo "... src/autoapp/Service/MediaSource/MicrophoneMediaSourceService.s"
	@echo "... src/autoapp/Service/NavigationStatus/NavigationStatusService.o"
	@echo "... src/autoapp/Service/NavigationStatus/NavigationStatusService.i"
	@echo "... src/autoapp/Service/NavigationStatus/NavigationStatusService.s"
	@echo "... src/autoapp/Service/PhoneStatus/PhoneStatusService.o"
	@echo "... src/autoapp/Service/PhoneStatus/PhoneStatusService.i"
	@echo "... src/autoapp/Service/PhoneStatus/PhoneStatusService.s"
	@echo "... src/autoapp/Service/Pinger.o"
	@echo "... src/autoapp/Service/Pinger.i"
	@echo "... src/autoapp/Service/Pinger.s"
	@echo "... src/autoapp/Service/Radio/RadioService.o"
	@echo "... src/autoapp/Service/Radio/RadioService.i"
	@echo "... src/autoapp/Service/Radio/RadioService.s"
	@echo "... src/autoapp/Service/Sensor/SensorService.o"
	@echo "... src/autoapp/Service/Sensor/SensorService.i"
	@echo "... src/autoapp/Service/Sensor/SensorService.s"
	@echo "... src/autoapp/Service/ServiceFactory.o"
	@echo "... src/autoapp/Service/ServiceFactory.i"
	@echo "... src/autoapp/Service/ServiceFactory.s"
	@echo "... src/autoapp/Service/VendorExtension/VendorExtensionService.o"
	@echo "... src/autoapp/Service/VendorExtension/VendorExtensionService.i"
	@echo "... src/autoapp/Service/VendorExtension/VendorExtensionService.s"
	@echo "... src/autoapp/Service/WifiProjection/WifiProjectionService.o"
	@echo "... src/autoapp/Service/WifiProjection/WifiProjectionService.i"
	@echo "... src/autoapp/Service/WifiProjection/WifiProjectionService.s"
	@echo "... src/autoapp/UI/ConnectDialog.o"
	@echo "... src/autoapp/UI/ConnectDialog.i"
	@echo "... src/autoapp/UI/ConnectDialog.s"
	@echo "... src/autoapp/UI/MainWindow.o"
	@echo "... src/autoapp/UI/MainWindow.i"
	@echo "... src/autoapp/UI/MainWindow.s"
	@echo "... src/autoapp/UI/SettingsWindow.o"
	@echo "... src/autoapp/UI/SettingsWindow.i"
	@echo "... src/autoapp/UI/SettingsWindow.s"
	@echo "... src/autoapp/UI/UpdateDialog.o"
	@echo "... src/autoapp/UI/UpdateDialog.i"
	@echo "... src/autoapp/UI/UpdateDialog.s"
	@echo "... src/autoapp/UI/WarningDialog.o"
	@echo "... src/autoapp/UI/WarningDialog.i"
	@echo "... src/autoapp/UI/WarningDialog.s"
	@echo "... src/autoapp/UI/dialog.o"
	@echo "... src/autoapp/UI/dialog.i"
	@echo "... src/autoapp/UI/dialog.s"
	@echo "... src/autoapp/autoapp.o"
	@echo "... src/autoapp/autoapp.i"
	@echo "... src/autoapp/autoapp.s"
	@echo "... src/btservice/AndroidBluetoothServer.o"
	@echo "... src/btservice/AndroidBluetoothServer.i"
	@echo "... src/btservice/AndroidBluetoothServer.s"
	@echo "... src/btservice/AndroidBluetoothService.o"
	@echo "... src/btservice/AndroidBluetoothService.i"
	@echo "... src/btservice/AndroidBluetoothService.s"
	@echo "... src/btservice/BluetoothHandler.o"
	@echo "... src/btservice/BluetoothHandler.i"
	@echo "... src/btservice/BluetoothHandler.s"
	@echo "... src/btservice/btservice.o"
	@echo "... src/btservice/btservice.i"
	@echo "... src/btservice/btservice.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

